-- Update exercise images (free-exercise-db, public domain)
BEGIN;

UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg' WHERE name_en = 'Bench Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg' WHERE name_en = 'Incline Bench Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg' WHERE name_en = 'Decline Bench Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg' WHERE name_en = 'Dumbbell Bench Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg' WHERE name_en = 'Incline Dumbbell Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg' WHERE name_en = 'Dumbbell Fly';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg' WHERE name_en = 'Incline Dumbbell Fly';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Cable_Flye/0.jpg' WHERE name_en = 'Cable Fly';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg' WHERE name_en = 'Push-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Up_Wide/0.jpg' WHERE name_en = 'Wide Push-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg' WHERE name_en = 'Decline Push-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Chest_Version/0.jpg' WHERE name_en = 'Dips (Chest)';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bench_Press/0.jpg' WHERE name_en = 'Machine Chest Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Svend_Press/0.jpg' WHERE name_en = 'Svend Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Press/0.jpg' WHERE name_en = 'Floor Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg' WHERE name_en = 'Deadlift';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg' WHERE name_en = 'Barbell Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg' WHERE name_en = 'Pull-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg' WHERE name_en = 'Chin-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' WHERE name_en = 'Lat Pulldown';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg' WHERE name_en = 'Close Grip Lat Pulldown';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' WHERE name_en = 'Cable Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg' WHERE name_en = 'T-Bar Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg' WHERE name_en = 'Dumbbell Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg' WHERE name_en = 'Face Pull';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg' WHERE name_en = 'Hyperextension';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg' WHERE name_en = 'Barbell Shrug';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg' WHERE name_en = 'Dumbbell Shrug';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight-Arm_Pulldown/0.jpg' WHERE name_en = 'Straight Arm Pulldown';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inverted_Row/0.jpg' WHERE name_en = 'Inverted Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg' WHERE name_en = 'Overhead Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg' WHERE name_en = 'Dumbbell Shoulder Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Press/0.jpg' WHERE name_en = 'Seated Dumbbell Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg' WHERE name_en = 'Arnold Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg' WHERE name_en = 'Lateral Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Lateral_Raise/0.jpg' WHERE name_en = 'Cable Lateral Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg' WHERE name_en = 'Front Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Flyes/0.jpg' WHERE name_en = 'Reverse Fly';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg' WHERE name_en = 'Reverse Pec Deck';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg' WHERE name_en = 'Upright Row';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg' WHERE name_en = 'Machine Shoulder Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Press/0.jpg' WHERE name_en = 'Push Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Barbell_Military_Press/0.jpg' WHERE name_en = 'Behind Neck Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Car_Drivers/0.jpg' WHERE name_en = 'Bus Driver';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg' WHERE name_en = 'Barbell Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg' WHERE name_en = 'EZ Bar Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg' WHERE name_en = 'Dumbbell Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg' WHERE name_en = 'Hammer Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg' WHERE name_en = 'Preacher Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg' WHERE name_en = 'Concentration Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/0.jpg' WHERE name_en = 'Cable Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg' WHERE name_en = 'Incline Dumbbell Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg' WHERE name_en = 'Spider Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Reverse_Curl/0.jpg' WHERE name_en = 'Reverse Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Bicep_Curl/0.jpg' WHERE name_en = 'Machine Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Drag_Curl/0.jpg' WHERE name_en = 'Drag Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross_Body_Hammer_Curl/0.jpg' WHERE name_en = 'Cross Body Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Zottman_Curl/0.jpg' WHERE name_en = 'Zottman Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg' WHERE name_en = 'Close Grip Bench Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg' WHERE name_en = 'Tricep Pushdown';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment/0.jpg' WHERE name_en = 'Rope Pushdown';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Overhead_Barbell_Triceps_Extension/0.jpg' WHERE name_en = 'Overhead Tricep Extension';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_One-Arm_Triceps_Extension/0.jpg' WHERE name_en = 'Dumbbell Overhead Extension';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Press/0.jpg' WHERE name_en = 'Skull Crusher';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg' WHERE name_en = 'Dips (Triceps)';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg' WHERE name_en = 'Kickback';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Push-Up_off_of_a_Dumbbell/0.jpg' WHERE name_en = 'Diamond Push-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg' WHERE name_en = 'Bench Dip';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/JM_Press/0.jpg' WHERE name_en = 'JM Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Triceps_Extension/0.jpg' WHERE name_en = 'Tricep Extension Machine';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg' WHERE name_en = 'Squat';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Squat_Clean_Grip/0.jpg' WHERE name_en = 'Front Squat';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg' WHERE name_en = 'Leg Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg' WHERE name_en = 'Leg Extension';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg' WHERE name_en = 'Hack Squat';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg' WHERE name_en = 'Goblet Squat';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg' WHERE name_en = 'Lunges';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Walking_Lunge/0.jpg' WHERE name_en = 'Walking Lunges';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Squat/0.jpg' WHERE name_en = 'Smith Machine Squat';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg' WHERE name_en = 'Romanian Deadlift';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg' WHERE name_en = 'Lying Leg Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg' WHERE name_en = 'Seated Leg Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/0.jpg' WHERE name_en = 'Stiff Leg Deadlift';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg' WHERE name_en = 'Good Morning';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Ham_Raise/0.jpg' WHERE name_en = 'Glute-Ham Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pull_Through/0.jpg' WHERE name_en = 'Cable Pull Through';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg' WHERE name_en = 'Hip Thrust';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg' WHERE name_en = 'Barbell Glute Bridge';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Step_Ups/0.jpg' WHERE name_en = 'Step Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg' WHERE name_en = 'Sumo Deadlift';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg' WHERE name_en = 'Standing Calf Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg' WHERE name_en = 'Seated Calf Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raises/0.jpg' WHERE name_en = 'Donkey Calf Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Calf_Raise/0.jpg' WHERE name_en = 'Smith Machine Calf Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg' WHERE name_en = 'Crunch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg' WHERE name_en = 'Plank';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg' WHERE name_en = 'Hanging Leg Raise';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg' WHERE name_en = 'Russian Twist';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg' WHERE name_en = 'Ab Wheel Rollout';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg' WHERE name_en = 'Cable Crunch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg' WHERE name_en = 'Mountain Climber';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg' WHERE name_en = 'Dead Bug';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg' WHERE name_en = 'Pallof Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Toe_Touchers/0.jpg' WHERE name_en = 'Toe Touch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flutter_Kicks/0.jpg' WHERE name_en = 'Flutter Kick';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg' WHERE name_en = 'Decline Crunch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Superman/0.jpg' WHERE name_en = 'Superman Hold';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg' WHERE name_en = 'Glute Bridge Hold';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Up_Barbell_Wrist_Curl_Over_A_Bench/0.jpg' WHERE name_en = 'Wrist Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Down_Wrist_Curl_Over_A_Bench/0.jpg' WHERE name_en = 'Reverse Wrist Curl';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmers_Walk/0.jpg' WHERE name_en = 'Farmer''s Walk';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plate_Pinch/0.jpg' WHERE name_en = 'Plate Pinch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg' WHERE name_en = 'Running';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jogging_Treadmill/0.jpg' WHERE name_en = 'Treadmill';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling/0.jpg' WHERE name_en = 'Cycling';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycling_Stationary/0.jpg' WHERE name_en = 'Stationary Bike';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/0.jpg' WHERE name_en = 'Rowing Machine';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stairmaster/0.jpg' WHERE name_en = 'Stair Climber';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/0.jpg' WHERE name_en = 'Elliptical';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battling_Ropes/0.jpg' WHERE name_en = 'Battle Ropes';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Box_Jump/0.jpg' WHERE name_en = 'Box Jump';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wind_Sprints/0.jpg' WHERE name_en = 'Sprints';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Leg_Butt_Kick/0.jpg' WHERE name_en = 'Butt Kicks';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Push/0.jpg' WHERE name_en = 'Sled Push';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Jerk/0.jpg' WHERE name_en = 'Clean and Jerk';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/0.jpg' WHERE name_en = 'Snatch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Power_Clean/0.jpg' WHERE name_en = 'Power Clean';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hang_Clean/0.jpg' WHERE name_en = 'Hang Clean';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Thruster/0.jpg' WHERE name_en = 'Thruster';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Squat_style/0.jpg' WHERE name_en = 'Turkish Get-Up';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg' WHERE name_en = 'Kettlebell Swing';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/0.jpg' WHERE name_en = 'Clean and Press';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hamstring_Stretch/0.jpg' WHERE name_en = 'Hamstring Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Quad_Stretch/0.jpg' WHERE name_en = 'Quad Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kneeling_Hip_Flexor/0.jpg' WHERE name_en = 'Hip Flexor Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dynamic_Chest_Stretch/0.jpg' WHERE name_en = 'Chest Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Shoulder_Stretch/0.jpg' WHERE name_en = 'Shoulder Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Stretch/0.jpg' WHERE name_en = 'Tricep Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Stretch_Hands_Against_Wall/0.jpg' WHERE name_en = 'Calf Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch/0.jpg' WHERE name_en = 'Cat-Cow Stretch';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Childs_Pose/0.jpg' WHERE name_en = 'Child''s Pose';
UPDATE exercises SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Worlds_Greatest_Stretch/0.jpg' WHERE name_en = 'World''s Greatest Stretch';

COMMIT;