"""
Recettes cétogènes statiques avec macros.
Chaque recette a un id, des noms FR/EN, un type de repas, des macros, et des objectifs compatibles.
"""

from typing import Any

KETO_RECIPES: list[dict[str, Any]] = [
    # ─── Petit-déjeuner ───────────────────────────────────────
    {
        "id": "keto_eggs_bacon",
        "name_fr": "Oeufs brouillés au bacon",
        "name_en": "Scrambled eggs with bacon",
        "meal_type": "breakfast",
        "calories": 450,
        "protein_g": 28,
        "carbs_g": 2,
        "fat_g": 36,
        "description_fr": "3 oeufs brouillés au beurre avec 3 tranches de bacon croustillant.",
        "description_en": "3 eggs scrambled in butter with 3 crispy bacon strips.",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_avocado_eggs",
        "name_fr": "Avocat farci aux oeufs",
        "name_en": "Avocado stuffed with eggs",
        "meal_type": "breakfast",
        "calories": 380,
        "protein_g": 18,
        "carbs_g": 4,
        "fat_g": 32,
        "description_fr": "Demi-avocat garni d'un oeuf cuit au four, sel et poivre.",
        "description_en": "Half avocado topped with a baked egg, salt and pepper.",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_chia_pudding",
        "name_fr": "Pudding de chia coco",
        "name_en": "Coconut chia pudding",
        "meal_type": "breakfast",
        "calories": 320,
        "protein_g": 8,
        "carbs_g": 6,
        "fat_g": 28,
        "description_fr": "Graines de chia trempées dans du lait de coco, avec quelques noix de pécan.",
        "description_en": "Chia seeds soaked in coconut milk, topped with pecans.",
        "goals": ["cut", "maintain"],
    },
    {
        "id": "keto_cream_cheese_pancakes",
        "name_fr": "Pancakes au cream cheese",
        "name_en": "Cream cheese pancakes",
        "meal_type": "breakfast",
        "calories": 400,
        "protein_g": 22,
        "carbs_g": 3,
        "fat_g": 34,
        "description_fr": "Pancakes à base d'oeufs et cream cheese, sans farine. Avec beurre.",
        "description_en": "Egg and cream cheese pancakes, flour-free. With butter.",
        "goals": ["maintain", "bulk", "recomp"],
    },

    # ─── Déjeuner ─────────────────────────────────────────────
    {
        "id": "keto_chicken_caesar",
        "name_fr": "Salade César au poulet grillé",
        "name_en": "Grilled chicken Caesar salad",
        "meal_type": "lunch",
        "calories": 520,
        "protein_g": 42,
        "carbs_g": 5,
        "fat_g": 38,
        "description_fr": "Poulet grillé, laitue romaine, parmesan, sauce César maison (sans croûtons).",
        "description_en": "Grilled chicken, romaine lettuce, parmesan, homemade Caesar dressing (no croutons).",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_salmon_salad",
        "name_fr": "Salade de saumon avocat",
        "name_en": "Salmon avocado salad",
        "meal_type": "lunch",
        "calories": 580,
        "protein_g": 35,
        "carbs_g": 6,
        "fat_g": 46,
        "description_fr": "Pavé de saumon grillé sur lit de roquette, avocat, huile d'olive et citron.",
        "description_en": "Grilled salmon fillet on arugula, avocado, olive oil and lemon.",
        "goals": ["bulk", "maintain", "recomp"],
    },
    {
        "id": "keto_burger_lettuce",
        "name_fr": "Burger sans pain (laitue)",
        "name_en": "Lettuce-wrapped burger",
        "meal_type": "lunch",
        "calories": 490,
        "protein_g": 38,
        "carbs_g": 4,
        "fat_g": 36,
        "description_fr": "Steak haché, fromage cheddar, tomate, cornichon dans des feuilles de laitue.",
        "description_en": "Beef patty, cheddar cheese, tomato, pickle wrapped in lettuce leaves.",
        "goals": ["maintain", "bulk", "recomp"],
    },
    {
        "id": "keto_zucchini_bolognese",
        "name_fr": "Courgetti bolognaise",
        "name_en": "Zucchini noodle bolognese",
        "meal_type": "lunch",
        "calories": 420,
        "protein_g": 32,
        "carbs_g": 8,
        "fat_g": 28,
        "description_fr": "Spaghetti de courgette avec sauce bolognaise maison (viande hachée, tomates, huile d'olive).",
        "description_en": "Zucchini noodles with homemade bolognese sauce (ground beef, tomatoes, olive oil).",
        "goals": ["cut", "maintain", "recomp"],
    },

    # ─── Dîner ────────────────────────────────────────────────
    {
        "id": "keto_steak_butter",
        "name_fr": "Entrecôte au beurre persillé",
        "name_en": "Ribeye with herb butter",
        "meal_type": "dinner",
        "calories": 650,
        "protein_g": 48,
        "carbs_g": 1,
        "fat_g": 50,
        "description_fr": "Entrecôte grillée avec beurre persillé, accompagnée d'épinards sautés.",
        "description_en": "Grilled ribeye with herb butter, served with sautéed spinach.",
        "goals": ["bulk", "strength", "maintain"],
    },
    {
        "id": "keto_chicken_broccoli",
        "name_fr": "Poulet brocoli crème",
        "name_en": "Creamy chicken broccoli",
        "meal_type": "dinner",
        "calories": 480,
        "protein_g": 40,
        "carbs_g": 6,
        "fat_g": 34,
        "description_fr": "Cuisses de poulet avec brocoli dans une sauce crème et parmesan.",
        "description_en": "Chicken thighs with broccoli in a cream and parmesan sauce.",
        "goals": ["maintain", "recomp", "bulk"],
    },
    {
        "id": "keto_shrimp_garlic",
        "name_fr": "Crevettes à l'ail et beurre",
        "name_en": "Garlic butter shrimp",
        "meal_type": "dinner",
        "calories": 380,
        "protein_g": 32,
        "carbs_g": 3,
        "fat_g": 26,
        "description_fr": "Crevettes sautées au beurre à l'ail avec courgettes grillées.",
        "description_en": "Shrimp sautéed in garlic butter with grilled zucchini.",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_stuffed_peppers",
        "name_fr": "Poivrons farcis keto",
        "name_en": "Keto stuffed peppers",
        "meal_type": "dinner",
        "calories": 440,
        "protein_g": 30,
        "carbs_g": 8,
        "fat_g": 32,
        "description_fr": "Poivrons farcis de viande hachée, fromage râpé et herbes, gratinés au four.",
        "description_en": "Bell peppers stuffed with ground meat, shredded cheese and herbs, oven-baked.",
        "goals": ["maintain", "bulk", "recomp"],
    },

    # ─── Snacks ───────────────────────────────────────────────
    {
        "id": "keto_fat_bombs",
        "name_fr": "Fat bombs chocolat-coco",
        "name_en": "Chocolate coconut fat bombs",
        "meal_type": "snack",
        "calories": 180,
        "protein_g": 3,
        "carbs_g": 2,
        "fat_g": 18,
        "description_fr": "Bouchées de beurre de coco, cacao et huile de coco. 2 pièces.",
        "description_en": "Coconut butter, cacao and coconut oil bites. 2 pieces.",
        "goals": ["maintain", "bulk"],
    },
    {
        "id": "keto_cheese_chips",
        "name_fr": "Chips de fromage",
        "name_en": "Cheese crisps",
        "meal_type": "snack",
        "calories": 150,
        "protein_g": 10,
        "carbs_g": 1,
        "fat_g": 12,
        "description_fr": "Rondelles de fromage (parmesan/cheddar) cuites au four jusqu'à croustillant.",
        "description_en": "Cheese rounds (parmesan/cheddar) baked until crispy.",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_guacamole",
        "name_fr": "Guacamole et crudités",
        "name_en": "Guacamole with veggies",
        "meal_type": "snack",
        "calories": 220,
        "protein_g": 4,
        "carbs_g": 8,
        "fat_g": 20,
        "description_fr": "Guacamole maison avec bâtonnets de concombre et céleri.",
        "description_en": "Homemade guacamole with cucumber and celery sticks.",
        "goals": ["cut", "maintain", "recomp"],
    },
    {
        "id": "keto_nuts_mix",
        "name_fr": "Mix de noix",
        "name_en": "Mixed nuts",
        "meal_type": "snack",
        "calories": 200,
        "protein_g": 6,
        "carbs_g": 4,
        "fat_g": 18,
        "description_fr": "Mélange de noix de macadamia, amandes et noix du Brésil. 30g.",
        "description_en": "Mix of macadamia nuts, almonds and Brazil nuts. 30g.",
        "goals": ["maintain", "bulk", "strength"],
    },
]


def get_recipes(meal_type: str | None = None, goal: str | None = None) -> list[dict]:
    """Filter recipes by meal type and/or goal."""
    results = KETO_RECIPES
    if meal_type:
        results = [r for r in results if r["meal_type"] == meal_type]
    if goal:
        results = [r for r in results if goal in r["goals"]]
    return results
