"""
Recettes statiques avec macros.
Chaque recette a un id, des noms FR/EN, un type de repas, des macros, des objectifs compatibles et des tags.
"""

from typing import Any

RECIPES: list[dict[str, Any]] = [
    # ═══════════════════════════════════════════════════════════════
    # PETIT-DÉJEUNER / BREAKFAST
    # ═══════════════════════════════════════════════════════════════

    # ─── Keto breakfasts (original) ──────────────────────────────
    {
        "id": "keto_eggs_bacon",
        "name_fr": "Oeufs brouillés au bacon",
        "name_en": "Scrambled eggs with bacon",
        "meal_type": "breakfast",
        "calories": 450,
        "protein_g": 28,
        "carbs_g": 2,
        "fat_g": 36,
        "description_fr": "3 oeufs brouillés au beurre avec 3 tranches de bacon croustillant.",
        "description_en": "3 eggs scrambled in butter with 3 crispy bacon strips.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_avocado_eggs",
        "name_fr": "Avocat farci aux oeufs",
        "name_en": "Avocado stuffed with eggs",
        "meal_type": "breakfast",
        "calories": 380,
        "protein_g": 18,
        "carbs_g": 4,
        "fat_g": 32,
        "description_fr": "Demi-avocat garni d'un oeuf cuit au four, sel et poivre.",
        "description_en": "Half avocado topped with a baked egg, salt and pepper.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_chia_pudding",
        "name_fr": "Pudding de chia coco",
        "name_en": "Coconut chia pudding",
        "meal_type": "breakfast",
        "calories": 320,
        "protein_g": 8,
        "carbs_g": 6,
        "fat_g": 28,
        "description_fr": "Graines de chia trempées dans du lait de coco, avec quelques noix de pécan.",
        "description_en": "Chia seeds soaked in coconut milk, topped with pecans.",
        "goals": ["cut", "maintain"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_cream_cheese_pancakes",
        "name_fr": "Pancakes au cream cheese",
        "name_en": "Cream cheese pancakes",
        "meal_type": "breakfast",
        "calories": 400,
        "protein_g": 22,
        "carbs_g": 3,
        "fat_g": 34,
        "description_fr": "Pancakes à base d'oeufs et cream cheese, sans farine. Avec beurre.",
        "description_en": "Egg and cream cheese pancakes, flour-free. With butter.",
        "goals": ["maintain", "bulk", "recomp"],
        "tags": ["keto", "low-carb"],
    },

    # ─── New breakfasts ──────────────────────────────────────────
    {
        "id": "overnight_oats",
        "name_fr": "Overnight oats fruits rouges",
        "name_en": "Berry overnight oats",
        "meal_type": "breakfast",
        "calories": 380,
        "protein_g": 14,
        "carbs_g": 55,
        "fat_g": 10,
        "description_fr": "Flocons d'avoine trempés dans du lait toute la nuit, garnis de fruits rouges et graines de chia.",
        "description_en": "Oats soaked in milk overnight, topped with mixed berries and chia seeds.",
        "goals": ["bulk", "endurance"],
        "tags": ["high-carb", "meal-prep", "vegetarian"],
    },
    {
        "id": "protein_pancakes",
        "name_fr": "Pancakes protéinés",
        "name_en": "Protein pancakes",
        "meal_type": "breakfast",
        "calories": 420,
        "protein_g": 35,
        "carbs_g": 38,
        "fat_g": 12,
        "description_fr": "Pancakes à base de whey, flocons d'avoine et banane. Nappés de sirop d'érable léger.",
        "description_en": "Pancakes made with whey, oats and banana. Drizzled with light maple syrup.",
        "goals": ["bulk", "maintain", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "greek_yogurt_granola",
        "name_fr": "Yaourt grec granola",
        "name_en": "Greek yogurt granola bowl",
        "meal_type": "breakfast",
        "calories": 350,
        "protein_g": 22,
        "carbs_g": 40,
        "fat_g": 10,
        "description_fr": "Yaourt grec 0% avec granola maison et un filet de miel.",
        "description_en": "Fat-free Greek yogurt with homemade granola and a drizzle of honey.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein", "vegetarian"],
    },
    {
        "id": "smoothie_bowl_protein",
        "name_fr": "Smoothie bowl protéiné",
        "name_en": "Protein smoothie bowl",
        "meal_type": "breakfast",
        "calories": 390,
        "protein_g": 30,
        "carbs_g": 45,
        "fat_g": 8,
        "description_fr": "Smoothie épais banane-myrtille-whey versé en bowl, garni de granola et coco râpée.",
        "description_en": "Thick banana-blueberry-whey smoothie poured into a bowl, topped with granola and shredded coconut.",
        "goals": ["bulk", "maintain"],
        "tags": ["high-protein", "high-carb"],
    },
    {
        "id": "tartines_avocat_saumon",
        "name_fr": "Tartines avocat saumon fumé",
        "name_en": "Avocado smoked salmon toast",
        "meal_type": "breakfast",
        "calories": 410,
        "protein_g": 22,
        "carbs_g": 30,
        "fat_g": 22,
        "description_fr": "Pain complet grillé avec avocat écrasé, saumon fumé, citron et graines de sésame.",
        "description_en": "Toasted whole wheat bread with mashed avocado, smoked salmon, lemon and sesame seeds.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "omelette_legumes",
        "name_fr": "Omelette aux légumes",
        "name_en": "Veggie omelette",
        "meal_type": "breakfast",
        "calories": 340,
        "protein_g": 24,
        "carbs_g": 6,
        "fat_g": 24,
        "description_fr": "Omelette 3 oeufs garnie de poivrons, champignons, oignons et fromage râpé.",
        "description_en": "3-egg omelette filled with bell peppers, mushrooms, onions and shredded cheese.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["low-carb", "vegetarian"],
    },
    {
        "id": "porridge_banane_peanut",
        "name_fr": "Porridge banane beurre de cacahuète",
        "name_en": "Banana peanut butter porridge",
        "meal_type": "breakfast",
        "calories": 520,
        "protein_g": 18,
        "carbs_g": 65,
        "fat_g": 20,
        "description_fr": "Porridge de flocons d'avoine avec banane écrasée et une cuillère de beurre de cacahuète.",
        "description_en": "Oat porridge with mashed banana and a spoonful of peanut butter.",
        "goals": ["bulk", "endurance"],
        "tags": ["high-carb", "vegetarian", "budget"],
    },
    {
        "id": "acai_bowl",
        "name_fr": "Bowl açaï",
        "name_en": "Acai bowl",
        "meal_type": "breakfast",
        "calories": 360,
        "protein_g": 8,
        "carbs_g": 52,
        "fat_g": 12,
        "description_fr": "Purée d'açaï mixée avec banane congelée, garnie de granola, fruits frais et coco.",
        "description_en": "Blended acai with frozen banana, topped with granola, fresh fruit and coconut.",
        "goals": ["bulk", "endurance"],
        "tags": ["high-carb", "vegan"],
    },

    # ═══════════════════════════════════════════════════════════════
    # DÉJEUNER / LUNCH
    # ═══════════════════════════════════════════════════════════════

    # ─── Keto lunches (original) ─────────────────────────────────
    {
        "id": "keto_chicken_caesar",
        "name_fr": "Salade César au poulet grillé",
        "name_en": "Grilled chicken Caesar salad",
        "meal_type": "lunch",
        "calories": 520,
        "protein_g": 42,
        "carbs_g": 5,
        "fat_g": 38,
        "description_fr": "Poulet grillé, laitue romaine, parmesan, sauce César maison (sans croûtons).",
        "description_en": "Grilled chicken, romaine lettuce, parmesan, homemade Caesar dressing (no croutons).",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_salmon_salad",
        "name_fr": "Salade de saumon avocat",
        "name_en": "Salmon avocado salad",
        "meal_type": "lunch",
        "calories": 580,
        "protein_g": 35,
        "carbs_g": 6,
        "fat_g": 46,
        "description_fr": "Pavé de saumon grillé sur lit de roquette, avocat, huile d'olive et citron.",
        "description_en": "Grilled salmon fillet on arugula, avocado, olive oil and lemon.",
        "goals": ["bulk", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_burger_lettuce",
        "name_fr": "Burger sans pain (laitue)",
        "name_en": "Lettuce-wrapped burger",
        "meal_type": "lunch",
        "calories": 490,
        "protein_g": 38,
        "carbs_g": 4,
        "fat_g": 36,
        "description_fr": "Steak haché, fromage cheddar, tomate, cornichon dans des feuilles de laitue.",
        "description_en": "Beef patty, cheddar cheese, tomato, pickle wrapped in lettuce leaves.",
        "goals": ["maintain", "bulk", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_zucchini_bolognese",
        "name_fr": "Courgetti bolognaise",
        "name_en": "Zucchini noodle bolognese",
        "meal_type": "lunch",
        "calories": 420,
        "protein_g": 32,
        "carbs_g": 8,
        "fat_g": 28,
        "description_fr": "Spaghetti de courgette avec sauce bolognaise maison (viande hachée, tomates, huile d'olive).",
        "description_en": "Zucchini noodles with homemade bolognese sauce (ground beef, tomatoes, olive oil).",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },

    # ─── New lunches ─────────────────────────────────────────────
    {
        "id": "chicken_rice_broccoli",
        "name_fr": "Poulet grillé riz brocoli",
        "name_en": "Grilled chicken rice broccoli",
        "meal_type": "lunch",
        "calories": 550,
        "protein_g": 45,
        "carbs_g": 52,
        "fat_g": 12,
        "description_fr": "Blanc de poulet grillé avec riz basmati et brocoli vapeur. Le classique du bodybuilding.",
        "description_en": "Grilled chicken breast with basmati rice and steamed broccoli. The bodybuilding classic.",
        "goals": ["bulk", "maintain", "recomp"],
        "tags": ["high-protein", "meal-prep", "budget"],
    },
    {
        "id": "salmon_teriyaki_bowl",
        "name_fr": "Bowl saumon teriyaki riz",
        "name_en": "Salmon teriyaki rice bowl",
        "meal_type": "lunch",
        "calories": 590,
        "protein_g": 38,
        "carbs_g": 55,
        "fat_g": 22,
        "description_fr": "Pavé de saumon glacé teriyaki sur riz à sushi, édamamé et avocat.",
        "description_en": "Teriyaki-glazed salmon over sushi rice with edamame and avocado.",
        "goals": ["bulk", "maintain"],
        "tags": ["high-protein", "high-carb"],
    },
    {
        "id": "caesar_salad_chicken",
        "name_fr": "Salade César poulet",
        "name_en": "Chicken Caesar salad",
        "meal_type": "lunch",
        "calories": 480,
        "protein_g": 40,
        "carbs_g": 22,
        "fat_g": 24,
        "description_fr": "Salade César classique avec poulet grillé, croûtons complets et parmesan.",
        "description_en": "Classic Caesar salad with grilled chicken, whole wheat croutons and parmesan.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "wrap_dinde_avocat",
        "name_fr": "Wrap dinde avocat",
        "name_en": "Turkey avocado wrap",
        "meal_type": "lunch",
        "calories": 430,
        "protein_g": 32,
        "carbs_g": 35,
        "fat_g": 18,
        "description_fr": "Tortilla complète garnie de tranches de dinde, avocat, laitue et moutarde au miel.",
        "description_en": "Whole wheat tortilla filled with turkey slices, avocado, lettuce and honey mustard.",
        "goals": ["maintain", "recomp"],
        "tags": ["quick"],
    },
    {
        "id": "pates_poulet_pesto",
        "name_fr": "Pâtes complètes poulet pesto",
        "name_en": "Whole wheat pesto chicken pasta",
        "meal_type": "lunch",
        "calories": 620,
        "protein_g": 42,
        "carbs_g": 58,
        "fat_g": 22,
        "description_fr": "Pâtes complètes al dente avec poulet émincé et pesto basilic maison.",
        "description_en": "Al dente whole wheat pasta with sliced chicken and homemade basil pesto.",
        "goals": ["bulk", "endurance"],
        "tags": ["high-protein", "high-carb"],
    },
    {
        "id": "quinoa_bowl_veggie",
        "name_fr": "Quinoa bowl veggie",
        "name_en": "Veggie quinoa bowl",
        "meal_type": "lunch",
        "calories": 420,
        "protein_g": 18,
        "carbs_g": 52,
        "fat_g": 16,
        "description_fr": "Quinoa avec pois chiches rôtis, patate douce, épinards et sauce tahini.",
        "description_en": "Quinoa with roasted chickpeas, sweet potato, spinach and tahini dressing.",
        "goals": ["maintain", "endurance"],
        "tags": ["vegan", "high-carb", "meal-prep"],
    },
    {
        "id": "steak_hache_patate_douce",
        "name_fr": "Steak haché patate douce",
        "name_en": "Beef patty with sweet potato",
        "meal_type": "lunch",
        "calories": 560,
        "protein_g": 38,
        "carbs_g": 45,
        "fat_g": 22,
        "description_fr": "Steak haché 5% grillé avec patate douce au four et haricots verts.",
        "description_en": "Grilled lean beef patty with baked sweet potato and green beans.",
        "goals": ["bulk", "maintain", "recomp"],
        "tags": ["high-protein", "meal-prep"],
    },
    {
        "id": "buddha_bowl_lentilles",
        "name_fr": "Buddha bowl lentilles",
        "name_en": "Lentil Buddha bowl",
        "meal_type": "lunch",
        "calories": 450,
        "protein_g": 22,
        "carbs_g": 55,
        "fat_g": 14,
        "description_fr": "Lentilles vertes, riz brun, carottes rôties, avocat et vinaigrette citronnée.",
        "description_en": "Green lentils, brown rice, roasted carrots, avocado and lemon vinaigrette.",
        "goals": ["maintain", "endurance"],
        "tags": ["vegan", "high-carb", "budget"],
    },
    {
        "id": "thon_salade_composee",
        "name_fr": "Thon en boîte salade composée",
        "name_en": "Canned tuna mixed salad",
        "meal_type": "lunch",
        "calories": 350,
        "protein_g": 35,
        "carbs_g": 18,
        "fat_g": 14,
        "description_fr": "Thon au naturel, maïs, tomates, haricots rouges, salade verte et vinaigrette légère.",
        "description_en": "Canned tuna in water, corn, tomatoes, red beans, lettuce and light vinaigrette.",
        "goals": ["cut", "recomp"],
        "tags": ["high-protein", "budget", "quick"],
    },
    {
        "id": "chili_con_carne",
        "name_fr": "Chili con carne",
        "name_en": "Chili con carne",
        "meal_type": "lunch",
        "calories": 510,
        "protein_g": 36,
        "carbs_g": 40,
        "fat_g": 18,
        "description_fr": "Boeuf haché mijoté avec haricots rouges, tomates, poivrons et épices. Servi avec riz.",
        "description_en": "Ground beef simmered with kidney beans, tomatoes, peppers and spices. Served with rice.",
        "goals": ["bulk", "maintain"],
        "tags": ["high-protein", "meal-prep"],
    },

    # ═══════════════════════════════════════════════════════════════
    # DÎNER / DINNER
    # ═══════════════════════════════════════════════════════════════

    # ─── Keto dinners (original) ─────────────────────────────────
    {
        "id": "keto_steak_butter",
        "name_fr": "Entrecôte au beurre persillé",
        "name_en": "Ribeye with herb butter",
        "meal_type": "dinner",
        "calories": 650,
        "protein_g": 48,
        "carbs_g": 1,
        "fat_g": 50,
        "description_fr": "Entrecôte grillée avec beurre persillé, accompagnée d'épinards sautés.",
        "description_en": "Grilled ribeye with herb butter, served with sautéed spinach.",
        "goals": ["bulk", "maintain"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_chicken_broccoli",
        "name_fr": "Poulet brocoli crème",
        "name_en": "Creamy chicken broccoli",
        "meal_type": "dinner",
        "calories": 480,
        "protein_g": 40,
        "carbs_g": 6,
        "fat_g": 34,
        "description_fr": "Cuisses de poulet avec brocoli dans une sauce crème et parmesan.",
        "description_en": "Chicken thighs with broccoli in a cream and parmesan sauce.",
        "goals": ["maintain", "recomp", "bulk"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_shrimp_garlic",
        "name_fr": "Crevettes à l'ail et beurre",
        "name_en": "Garlic butter shrimp",
        "meal_type": "dinner",
        "calories": 380,
        "protein_g": 32,
        "carbs_g": 3,
        "fat_g": 26,
        "description_fr": "Crevettes sautées au beurre à l'ail avec courgettes grillées.",
        "description_en": "Shrimp sautéed in garlic butter with grilled zucchini.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_stuffed_peppers",
        "name_fr": "Poivrons farcis keto",
        "name_en": "Keto stuffed peppers",
        "meal_type": "dinner",
        "calories": 440,
        "protein_g": 30,
        "carbs_g": 8,
        "fat_g": 32,
        "description_fr": "Poivrons farcis de viande hachée, fromage râpé et herbes, gratinés au four.",
        "description_en": "Bell peppers stuffed with ground meat, shredded cheese and herbs, oven-baked.",
        "goals": ["maintain", "bulk", "recomp"],
        "tags": ["keto", "low-carb"],
    },

    # ─── New dinners ─────────────────────────────────────────────
    {
        "id": "saumon_four_legumes",
        "name_fr": "Saumon au four légumes rôtis",
        "name_en": "Oven-baked salmon with roasted vegetables",
        "meal_type": "dinner",
        "calories": 480,
        "protein_g": 38,
        "carbs_g": 20,
        "fat_g": 26,
        "description_fr": "Filet de saumon cuit au four avec courgettes, poivrons et tomates cerises rôtis à l'huile d'olive.",
        "description_en": "Oven-baked salmon fillet with roasted zucchini, bell peppers and cherry tomatoes in olive oil.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "poulet_curry_coco",
        "name_fr": "Poulet curry coco riz",
        "name_en": "Coconut curry chicken with rice",
        "meal_type": "dinner",
        "calories": 600,
        "protein_g": 40,
        "carbs_g": 52,
        "fat_g": 22,
        "description_fr": "Morceaux de poulet mijotés dans une sauce curry-lait de coco, servis avec riz basmati.",
        "description_en": "Chicken pieces simmered in curry-coconut milk sauce, served with basmati rice.",
        "goals": ["bulk", "maintain"],
        "tags": ["high-protein", "high-carb"],
    },
    {
        "id": "stir_fry_boeuf_nouilles",
        "name_fr": "Stir-fry boeuf nouilles",
        "name_en": "Beef noodle stir-fry",
        "meal_type": "dinner",
        "calories": 540,
        "protein_g": 36,
        "carbs_g": 48,
        "fat_g": 20,
        "description_fr": "Lamelles de boeuf sautées au wok avec nouilles, poivrons, oignons et sauce soja.",
        "description_en": "Wok-fried beef strips with noodles, bell peppers, onions and soy sauce.",
        "goals": ["bulk", "maintain"],
        "tags": ["high-protein", "high-carb", "quick"],
    },
    {
        "id": "omelette_champignons_fromage",
        "name_fr": "Omelette champignons fromage",
        "name_en": "Mushroom cheese omelette",
        "meal_type": "dinner",
        "calories": 380,
        "protein_g": 28,
        "carbs_g": 4,
        "fat_g": 28,
        "description_fr": "Omelette 3 oeufs garnie de champignons de Paris sautés et gruyère fondu.",
        "description_en": "3-egg omelette filled with sautéed button mushrooms and melted Gruyere cheese.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["low-carb", "quick", "vegetarian", "budget"],
    },
    {
        "id": "soupe_lentilles_corail",
        "name_fr": "Soupe de lentilles corail",
        "name_en": "Red lentil soup",
        "meal_type": "dinner",
        "calories": 320,
        "protein_g": 18,
        "carbs_g": 42,
        "fat_g": 8,
        "description_fr": "Lentilles corail mijotées avec oignons, carottes, cumin et lait de coco. Servie avec pain complet.",
        "description_en": "Red lentils simmered with onions, carrots, cumin and coconut milk. Served with whole wheat bread.",
        "goals": ["cut", "maintain"],
        "tags": ["vegan", "budget", "high-carb"],
    },
    {
        "id": "pave_thon_quinoa",
        "name_fr": "Pavé de thon quinoa",
        "name_en": "Tuna steak with quinoa",
        "meal_type": "dinner",
        "calories": 470,
        "protein_g": 44,
        "carbs_g": 32,
        "fat_g": 16,
        "description_fr": "Pavé de thon snacké, quinoa et légumes grillés (courgette, aubergine) avec filet de citron.",
        "description_en": "Seared tuna steak, quinoa and grilled vegetables (zucchini, eggplant) with a squeeze of lemon.",
        "goals": ["cut", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "blanquette_poulet_allegee",
        "name_fr": "Blanquette de poulet allégée",
        "name_en": "Light chicken blanquette",
        "meal_type": "dinner",
        "calories": 430,
        "protein_g": 38,
        "carbs_g": 30,
        "fat_g": 16,
        "description_fr": "Poulet mijoté dans une sauce légère au yaourt, carottes et champignons. Servi avec riz.",
        "description_en": "Chicken simmered in a light yogurt sauce with carrots and mushrooms. Served with rice.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein"],
    },
    {
        "id": "wok_crevettes_legumes",
        "name_fr": "Wok crevettes légumes",
        "name_en": "Shrimp vegetable stir-fry",
        "meal_type": "dinner",
        "calories": 340,
        "protein_g": 30,
        "carbs_g": 18,
        "fat_g": 14,
        "description_fr": "Crevettes sautées au wok avec brocoli, carottes, pois mange-tout et sauce gingembre-soja.",
        "description_en": "Wok-tossed shrimp with broccoli, carrots, snow peas and ginger-soy sauce.",
        "goals": ["cut", "recomp"],
        "tags": ["high-protein", "low-carb", "quick"],
    },
    {
        "id": "gratin_courgettes_poulet",
        "name_fr": "Gratin de courgettes au poulet",
        "name_en": "Chicken zucchini gratin",
        "meal_type": "dinner",
        "calories": 420,
        "protein_g": 36,
        "carbs_g": 10,
        "fat_g": 26,
        "description_fr": "Courgettes et poulet émincé gratinés au four avec béchamel légère et emmental.",
        "description_en": "Sliced zucchini and chicken baked with light bechamel and Swiss cheese.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein", "low-carb"],
    },

    # ═══════════════════════════════════════════════════════════════
    # SNACKS / COLLATIONS
    # ═══════════════════════════════════════════════════════════════

    # ─── Keto snacks (original) ──────────────────────────────────
    {
        "id": "keto_fat_bombs",
        "name_fr": "Fat bombs chocolat-coco",
        "name_en": "Chocolate coconut fat bombs",
        "meal_type": "snack",
        "calories": 180,
        "protein_g": 3,
        "carbs_g": 2,
        "fat_g": 18,
        "description_fr": "Bouchées de beurre de coco, cacao et huile de coco. 2 pièces.",
        "description_en": "Coconut butter, cacao and coconut oil bites. 2 pieces.",
        "goals": ["maintain", "bulk"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_cheese_chips",
        "name_fr": "Chips de fromage",
        "name_en": "Cheese crisps",
        "meal_type": "snack",
        "calories": 150,
        "protein_g": 10,
        "carbs_g": 1,
        "fat_g": 12,
        "description_fr": "Rondelles de fromage (parmesan/cheddar) cuites au four jusqu'à croustillant.",
        "description_en": "Cheese rounds (parmesan/cheddar) baked until crispy.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_guacamole",
        "name_fr": "Guacamole et crudités",
        "name_en": "Guacamole with veggies",
        "meal_type": "snack",
        "calories": 220,
        "protein_g": 4,
        "carbs_g": 8,
        "fat_g": 20,
        "description_fr": "Guacamole maison avec bâtonnets de concombre et céleri.",
        "description_en": "Homemade guacamole with cucumber and celery sticks.",
        "goals": ["cut", "maintain", "recomp"],
        "tags": ["keto", "low-carb"],
    },
    {
        "id": "keto_nuts_mix",
        "name_fr": "Mix de noix",
        "name_en": "Mixed nuts",
        "meal_type": "snack",
        "calories": 200,
        "protein_g": 6,
        "carbs_g": 4,
        "fat_g": 18,
        "description_fr": "Mélange de noix de macadamia, amandes et noix du Brésil. 30g.",
        "description_en": "Mix of macadamia nuts, almonds and Brazil nuts. 30g.",
        "goals": ["maintain", "bulk"],
        "tags": ["keto", "low-carb"],
    },

    # ─── New snacks ──────────────────────────────────────────────
    {
        "id": "protein_shake_banane",
        "name_fr": "Protein shake banane",
        "name_en": "Banana protein shake",
        "meal_type": "snack",
        "calories": 280,
        "protein_g": 30,
        "carbs_g": 30,
        "fat_g": 4,
        "description_fr": "Whey protéine mixée avec banane, lait écrémé et glaçons.",
        "description_en": "Whey protein blended with banana, skim milk and ice.",
        "goals": ["bulk", "maintain", "recomp"],
        "tags": ["high-protein", "quick"],
    },
    {
        "id": "houmous_crudites",
        "name_fr": "Houmous crudités",
        "name_en": "Hummus with raw veggies",
        "meal_type": "snack",
        "calories": 190,
        "protein_g": 8,
        "carbs_g": 18,
        "fat_g": 10,
        "description_fr": "Houmous maison avec bâtonnets de carottes, concombre et poivron.",
        "description_en": "Homemade hummus with carrot, cucumber and bell pepper sticks.",
        "goals": ["cut", "maintain"],
        "tags": ["vegan", "budget"],
    },
    {
        "id": "fromage_blanc_fruits_rouges",
        "name_fr": "Fromage blanc fruits rouges",
        "name_en": "Quark with mixed berries",
        "meal_type": "snack",
        "calories": 150,
        "protein_g": 18,
        "carbs_g": 14,
        "fat_g": 2,
        "description_fr": "Fromage blanc 0% avec un mélange de fraises, framboises et myrtilles.",
        "description_en": "Fat-free quark topped with strawberries, raspberries and blueberries.",
        "goals": ["cut", "recomp"],
        "tags": ["high-protein", "budget"],
    },
    {
        "id": "energy_balls_dattes",
        "name_fr": "Energy balls dattes cacao",
        "name_en": "Date cacao energy balls",
        "meal_type": "snack",
        "calories": 160,
        "protein_g": 4,
        "carbs_g": 22,
        "fat_g": 7,
        "description_fr": "Boules d'énergie à base de dattes, cacao, flocons d'avoine et beurre de cacahuète. 2 pièces.",
        "description_en": "Energy balls made with dates, cacao, oats and peanut butter. 2 pieces.",
        "goals": ["bulk", "endurance"],
        "tags": ["vegan", "meal-prep", "high-carb"],
    },
    {
        "id": "yaourt_grec_miel_noix",
        "name_fr": "Yaourt grec miel noix",
        "name_en": "Greek yogurt with honey and walnuts",
        "meal_type": "snack",
        "calories": 220,
        "protein_g": 16,
        "carbs_g": 20,
        "fat_g": 8,
        "description_fr": "Yaourt grec nature avec un filet de miel et cerneaux de noix.",
        "description_en": "Plain Greek yogurt with a drizzle of honey and walnut halves.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein", "vegetarian"],
    },
    {
        "id": "cottage_cheese_ananas",
        "name_fr": "Cottage cheese ananas",
        "name_en": "Cottage cheese with pineapple",
        "meal_type": "snack",
        "calories": 170,
        "protein_g": 20,
        "carbs_g": 16,
        "fat_g": 2,
        "description_fr": "Cottage cheese allégé avec morceaux d'ananas frais.",
        "description_en": "Low-fat cottage cheese with fresh pineapple chunks.",
        "goals": ["cut", "recomp"],
        "tags": ["high-protein", "budget"],
    },
    {
        "id": "rice_cakes_peanut_butter",
        "name_fr": "Rice cakes beurre de cacahuète",
        "name_en": "Rice cakes with peanut butter",
        "meal_type": "snack",
        "calories": 210,
        "protein_g": 8,
        "carbs_g": 24,
        "fat_g": 10,
        "description_fr": "2 galettes de riz soufflé tartinées de beurre de cacahuète.",
        "description_en": "2 puffed rice cakes spread with peanut butter.",
        "goals": ["bulk", "endurance"],
        "tags": ["vegan", "quick", "high-carb"],
    },
    {
        "id": "edamame_sel",
        "name_fr": "Edamame sel",
        "name_en": "Salted edamame",
        "meal_type": "snack",
        "calories": 120,
        "protein_g": 12,
        "carbs_g": 8,
        "fat_g": 5,
        "description_fr": "Fèves de soja édamamé cuites à la vapeur et saupoudrées de fleur de sel.",
        "description_en": "Steamed edamame beans sprinkled with sea salt.",
        "goals": ["cut", "recomp"],
        "tags": ["vegan", "high-protein", "quick"],
    },
    {
        "id": "banana_oat_muffins",
        "name_fr": "Muffins banane avoine",
        "name_en": "Banana oat muffins",
        "meal_type": "snack",
        "calories": 180,
        "protein_g": 6,
        "carbs_g": 28,
        "fat_g": 5,
        "description_fr": "Muffins maison à base de flocons d'avoine, banane mûre et pépites de chocolat noir. 1 muffin.",
        "description_en": "Homemade muffins made with oats, ripe banana and dark chocolate chips. 1 muffin.",
        "goals": ["bulk", "endurance"],
        "tags": ["vegetarian", "meal-prep", "high-carb"],
    },

    # ─── Extra lunch recipes ─────────────────────────────────────
    {
        "id": "poke_bowl_saumon",
        "name_fr": "Poké bowl saumon",
        "name_en": "Salmon poke bowl",
        "meal_type": "lunch",
        "calories": 520,
        "protein_g": 32,
        "carbs_g": 50,
        "fat_g": 20,
        "description_fr": "Riz vinaigré, saumon cru mariné soja-sésame, avocat, édamamé et concombre.",
        "description_en": "Seasoned rice, soy-sesame marinated raw salmon, avocado, edamame and cucumber.",
        "goals": ["maintain", "bulk"],
        "tags": ["high-protein"],
    },
    {
        "id": "dahl_lentilles",
        "name_fr": "Dahl de lentilles riz",
        "name_en": "Lentil dahl with rice",
        "meal_type": "lunch",
        "calories": 440,
        "protein_g": 20,
        "carbs_g": 62,
        "fat_g": 10,
        "description_fr": "Lentilles corail mijotées aux épices indiennes (curcuma, cumin, coriandre) servies sur riz basmati.",
        "description_en": "Red lentils simmered with Indian spices (turmeric, cumin, coriander) served over basmati rice.",
        "goals": ["bulk", "endurance"],
        "tags": ["vegan", "high-carb", "budget"],
    },

    # ─── Extra dinner recipes ────────────────────────────────────
    {
        "id": "filet_cabillaud_puree",
        "name_fr": "Filet de cabillaud purée maison",
        "name_en": "Cod fillet with mashed potatoes",
        "meal_type": "dinner",
        "calories": 400,
        "protein_g": 35,
        "carbs_g": 35,
        "fat_g": 12,
        "description_fr": "Filet de cabillaud au four avec purée de pommes de terre maison et haricots verts.",
        "description_en": "Oven-baked cod fillet with homemade mashed potatoes and green beans.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein", "budget"],
    },
    {
        "id": "tacos_poulet_maison",
        "name_fr": "Tacos poulet maison",
        "name_en": "Homemade chicken tacos",
        "meal_type": "dinner",
        "calories": 480,
        "protein_g": 34,
        "carbs_g": 38,
        "fat_g": 18,
        "description_fr": "Tortillas de maïs garnies de poulet épicé, guacamole, tomates et oignons rouges.",
        "description_en": "Corn tortillas filled with spiced chicken, guacamole, tomatoes and red onions.",
        "goals": ["maintain", "bulk"],
        "tags": ["high-protein", "quick"],
    },

    # ─── Extra breakfast recipe ──────────────────────────────────
    {
        "id": "eggs_toast_complet",
        "name_fr": "Oeufs pochés toast complet",
        "name_en": "Poached eggs on whole wheat toast",
        "meal_type": "breakfast",
        "calories": 350,
        "protein_g": 22,
        "carbs_g": 28,
        "fat_g": 16,
        "description_fr": "2 oeufs pochés sur toast de pain complet avec épinards frais et poivre.",
        "description_en": "2 poached eggs on whole wheat toast with fresh spinach and pepper.",
        "goals": ["maintain", "recomp"],
        "tags": ["high-protein", "quick", "vegetarian"],
    },
]


def get_recipes(
    meal_type: str | None = None,
    goal: str | None = None,
    tag: str | None = None,
) -> list[dict]:
    """Filter recipes by meal type, goal and/or tag."""
    results = list(RECIPES)
    if meal_type:
        results = [r for r in results if r["meal_type"] == meal_type]
    if goal:
        results = [r for r in results if goal in r["goals"]]
    if tag:
        results = [r for r in results if tag in r.get("tags", [])]
    return results
