from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.exercise import Exercise

EXERCISES: list[dict] = [
    # ─── Chest (Pectoraux) ──────────────────────────────────────
    {"name_key": "exercise.bench_press", "name_en": "Bench Press", "name_fr": "Développé couché", "muscle_group": "chest", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.incline_bench_press", "name_en": "Incline Bench Press", "name_fr": "Développé incliné", "muscle_group": "chest", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.decline_bench_press", "name_en": "Decline Bench Press", "name_fr": "Développé décliné", "muscle_group": "chest", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.dumbbell_bench_press", "name_en": "Dumbbell Bench Press", "name_fr": "Développé couché haltères", "muscle_group": "chest", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.incline_dumbbell_press", "name_en": "Incline Dumbbell Press", "name_fr": "Développé incliné haltères", "muscle_group": "chest", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.decline_dumbbell_press", "name_en": "Decline Dumbbell Press", "name_fr": "Développé décliné haltères", "muscle_group": "chest", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.dumbbell_fly", "name_en": "Dumbbell Fly", "name_fr": "Écarté haltères", "muscle_group": "chest", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.incline_dumbbell_fly", "name_en": "Incline Dumbbell Fly", "name_fr": "Écarté incliné haltères", "muscle_group": "chest", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.cable_fly", "name_en": "Cable Fly", "name_fr": "Écarté poulie", "muscle_group": "chest", "category": "cable", "is_compound": False},
    {"name_key": "exercise.low_cable_fly", "name_en": "Low Cable Fly", "name_fr": "Écarté poulie basse", "muscle_group": "chest", "category": "cable", "is_compound": False},
    {"name_key": "exercise.high_cable_fly", "name_en": "High Cable Fly", "name_fr": "Écarté poulie haute", "muscle_group": "chest", "category": "cable", "is_compound": False},
    {"name_key": "exercise.push_up", "name_en": "Push-Up", "name_fr": "Pompes", "muscle_group": "chest", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.wide_push_up", "name_en": "Wide Push-Up", "name_fr": "Pompes larges", "muscle_group": "chest", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.decline_push_up", "name_en": "Decline Push-Up", "name_fr": "Pompes déclinées", "muscle_group": "chest", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.chest_dips", "name_en": "Dips (Chest)", "name_fr": "Dips pectoraux", "muscle_group": "chest", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.pec_deck", "name_en": "Pec Deck", "name_fr": "Pec Deck", "muscle_group": "chest", "category": "machine", "is_compound": False},
    {"name_key": "exercise.machine_chest_press", "name_en": "Machine Chest Press", "name_fr": "Presse pectorale machine", "muscle_group": "chest", "category": "machine", "is_compound": True},
    {"name_key": "exercise.landmine_press", "name_en": "Landmine Press", "name_fr": "Landmine Press", "muscle_group": "chest", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.svend_press", "name_en": "Svend Press", "name_fr": "Svend Press", "muscle_group": "chest", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.floor_press", "name_en": "Floor Press", "name_fr": "Développé au sol", "muscle_group": "chest", "category": "barbell", "is_compound": True},

    # ─── Back (Dos) ─────────────────────────────────────────────
    {"name_key": "exercise.deadlift", "name_en": "Deadlift", "name_fr": "Soulevé de terre", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.barbell_row", "name_en": "Barbell Row", "name_fr": "Rowing barre", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.pendlay_row", "name_en": "Pendlay Row", "name_fr": "Rowing Pendlay", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.pull_up", "name_en": "Pull-Up", "name_fr": "Traction", "muscle_group": "back", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.chin_up", "name_en": "Chin-Up", "name_fr": "Traction supination", "muscle_group": "back", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.wide_grip_pull_up", "name_en": "Wide Grip Pull-Up", "name_fr": "Traction prise large", "muscle_group": "back", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.lat_pulldown", "name_en": "Lat Pulldown", "name_fr": "Tirage poitrine", "muscle_group": "back", "category": "cable", "is_compound": True},
    {"name_key": "exercise.close_grip_lat_pulldown", "name_en": "Close Grip Lat Pulldown", "name_fr": "Tirage poitrine prise serrée", "muscle_group": "back", "category": "cable", "is_compound": True},
    {"name_key": "exercise.cable_row", "name_en": "Cable Row", "name_fr": "Tirage poulie basse", "muscle_group": "back", "category": "cable", "is_compound": True},
    {"name_key": "exercise.t_bar_row", "name_en": "T-Bar Row", "name_fr": "Rowing T-Bar", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.dumbbell_row", "name_en": "Dumbbell Row", "name_fr": "Rowing haltère", "muscle_group": "back", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.chest_supported_row", "name_en": "Chest Supported Row", "name_fr": "Rowing poitrine supportée", "muscle_group": "back", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.face_pull", "name_en": "Face Pull", "name_fr": "Face Pull", "muscle_group": "back", "category": "cable", "is_compound": True},
    {"name_key": "exercise.hyperextension", "name_en": "Hyperextension", "name_fr": "Hyperextension", "muscle_group": "back", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.shrug", "name_en": "Barbell Shrug", "name_fr": "Haussement d'épaules barre", "muscle_group": "back", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.dumbbell_shrug", "name_en": "Dumbbell Shrug", "name_fr": "Haussement d'épaules haltères", "muscle_group": "back", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.straight_arm_pulldown", "name_en": "Straight Arm Pulldown", "name_fr": "Pulldown bras tendus", "muscle_group": "back", "category": "cable", "is_compound": False},
    {"name_key": "exercise.inverted_row", "name_en": "Inverted Row", "name_fr": "Rowing inversé", "muscle_group": "back", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.meadows_row", "name_en": "Meadows Row", "name_fr": "Meadows Row", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.seal_row", "name_en": "Seal Row", "name_fr": "Seal Row", "muscle_group": "back", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.machine_row", "name_en": "Machine Row", "name_fr": "Rowing machine", "muscle_group": "back", "category": "machine", "is_compound": True},

    # ─── Shoulders (Épaules) ────────────────────────────────────
    {"name_key": "exercise.overhead_press", "name_en": "Overhead Press", "name_fr": "Développé militaire", "muscle_group": "shoulders", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.dumbbell_shoulder_press", "name_en": "Dumbbell Shoulder Press", "name_fr": "Développé épaules haltères", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.seated_dumbbell_press", "name_en": "Seated Dumbbell Press", "name_fr": "Développé épaules assis", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.arnold_press", "name_en": "Arnold Press", "name_fr": "Arnold Press", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.lateral_raise", "name_en": "Lateral Raise", "name_fr": "Élévation latérale", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.cable_lateral_raise", "name_en": "Cable Lateral Raise", "name_fr": "Élévation latérale poulie", "muscle_group": "shoulders", "category": "cable", "is_compound": False},
    {"name_key": "exercise.front_raise", "name_en": "Front Raise", "name_fr": "Élévation frontale", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.cable_front_raise", "name_en": "Cable Front Raise", "name_fr": "Élévation frontale poulie", "muscle_group": "shoulders", "category": "cable", "is_compound": False},
    {"name_key": "exercise.reverse_fly", "name_en": "Reverse Fly", "name_fr": "Oiseau", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.reverse_pec_deck", "name_en": "Reverse Pec Deck", "name_fr": "Oiseau machine", "muscle_group": "shoulders", "category": "machine", "is_compound": False},
    {"name_key": "exercise.upright_row", "name_en": "Upright Row", "name_fr": "Tirage menton", "muscle_group": "shoulders", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.machine_shoulder_press", "name_en": "Machine Shoulder Press", "name_fr": "Presse épaules machine", "muscle_group": "shoulders", "category": "machine", "is_compound": True},
    {"name_key": "exercise.push_press", "name_en": "Push Press", "name_fr": "Push Press", "muscle_group": "shoulders", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.behind_neck_press", "name_en": "Behind Neck Press", "name_fr": "Développé nuque", "muscle_group": "shoulders", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.lu_raise", "name_en": "Lu Raise", "name_fr": "Lu Raise", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.bus_driver", "name_en": "Bus Driver", "name_fr": "Bus Driver", "muscle_group": "shoulders", "category": "dumbbell", "is_compound": False},

    # ─── Biceps ─────────────────────────────────────────────────
    {"name_key": "exercise.barbell_curl", "name_en": "Barbell Curl", "name_fr": "Curl barre", "muscle_group": "biceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.ez_bar_curl", "name_en": "EZ Bar Curl", "name_fr": "Curl barre EZ", "muscle_group": "biceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.dumbbell_curl", "name_en": "Dumbbell Curl", "name_fr": "Curl haltère", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.hammer_curl", "name_en": "Hammer Curl", "name_fr": "Curl marteau", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.preacher_curl", "name_en": "Preacher Curl", "name_fr": "Curl pupitre", "muscle_group": "biceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.concentration_curl", "name_en": "Concentration Curl", "name_fr": "Curl concentration", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.cable_curl", "name_en": "Cable Curl", "name_fr": "Curl poulie", "muscle_group": "biceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.incline_dumbbell_curl", "name_en": "Incline Dumbbell Curl", "name_fr": "Curl incliné", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.spider_curl", "name_en": "Spider Curl", "name_fr": "Spider Curl", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.bayesian_curl", "name_en": "Bayesian Curl", "name_fr": "Curl Bayesian", "muscle_group": "biceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.reverse_curl", "name_en": "Reverse Curl", "name_fr": "Curl inversé", "muscle_group": "biceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.machine_curl", "name_en": "Machine Curl", "name_fr": "Curl machine", "muscle_group": "biceps", "category": "machine", "is_compound": False},
    {"name_key": "exercise.drag_curl", "name_en": "Drag Curl", "name_fr": "Drag Curl", "muscle_group": "biceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.cross_body_curl", "name_en": "Cross Body Curl", "name_fr": "Curl croisé", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.zottman_curl", "name_en": "Zottman Curl", "name_fr": "Curl Zottman", "muscle_group": "biceps", "category": "dumbbell", "is_compound": False},

    # ─── Triceps ────────────────────────────────────────────────
    {"name_key": "exercise.close_grip_bench_press", "name_en": "Close Grip Bench Press", "name_fr": "Développé couché serré", "muscle_group": "triceps", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.tricep_pushdown", "name_en": "Tricep Pushdown", "name_fr": "Extension poulie haute", "muscle_group": "triceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.rope_pushdown", "name_en": "Rope Pushdown", "name_fr": "Extension corde poulie haute", "muscle_group": "triceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.overhead_tricep_extension", "name_en": "Overhead Tricep Extension", "name_fr": "Extension triceps au-dessus de la tête", "muscle_group": "triceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.dumbbell_overhead_extension", "name_en": "Dumbbell Overhead Extension", "name_fr": "Extension triceps haltère", "muscle_group": "triceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.skull_crusher", "name_en": "Skull Crusher", "name_fr": "Barre au front", "muscle_group": "triceps", "category": "barbell", "is_compound": False},
    {"name_key": "exercise.tricep_dips", "name_en": "Dips (Triceps)", "name_fr": "Dips triceps", "muscle_group": "triceps", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.kickback", "name_en": "Kickback", "name_fr": "Kickback", "muscle_group": "triceps", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.cable_kickback", "name_en": "Cable Kickback", "name_fr": "Kickback poulie", "muscle_group": "triceps", "category": "cable", "is_compound": False},
    {"name_key": "exercise.diamond_push_up", "name_en": "Diamond Push-Up", "name_fr": "Pompes diamant", "muscle_group": "triceps", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.bench_dip", "name_en": "Bench Dip", "name_fr": "Dips sur banc", "muscle_group": "triceps", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.jm_press", "name_en": "JM Press", "name_fr": "JM Press", "muscle_group": "triceps", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.tricep_machine", "name_en": "Tricep Extension Machine", "name_fr": "Extension triceps machine", "muscle_group": "triceps", "category": "machine", "is_compound": False},

    # ─── Quads (Quadriceps) ─────────────────────────────────────
    {"name_key": "exercise.squat", "name_en": "Squat", "name_fr": "Squat", "muscle_group": "quads", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.front_squat", "name_en": "Front Squat", "name_fr": "Front Squat", "muscle_group": "quads", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.leg_press", "name_en": "Leg Press", "name_fr": "Presse à cuisses", "muscle_group": "quads", "category": "machine", "is_compound": True},
    {"name_key": "exercise.leg_extension", "name_en": "Leg Extension", "name_fr": "Extension de jambes", "muscle_group": "quads", "category": "machine", "is_compound": False},
    {"name_key": "exercise.hack_squat", "name_en": "Hack Squat", "name_fr": "Hack Squat", "muscle_group": "quads", "category": "machine", "is_compound": True},
    {"name_key": "exercise.bulgarian_split_squat", "name_en": "Bulgarian Split Squat", "name_fr": "Split Squat bulgare", "muscle_group": "quads", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.goblet_squat", "name_en": "Goblet Squat", "name_fr": "Goblet Squat", "muscle_group": "quads", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.lunges", "name_en": "Lunges", "name_fr": "Fentes", "muscle_group": "quads", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.walking_lunges", "name_en": "Walking Lunges", "name_fr": "Fentes marchées", "muscle_group": "quads", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.reverse_lunges", "name_en": "Reverse Lunges", "name_fr": "Fentes arrière", "muscle_group": "quads", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.sissy_squat", "name_en": "Sissy Squat", "name_fr": "Sissy Squat", "muscle_group": "quads", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.smith_machine_squat", "name_en": "Smith Machine Squat", "name_fr": "Squat Smith machine", "muscle_group": "quads", "category": "machine", "is_compound": True},
    {"name_key": "exercise.pendulum_squat", "name_en": "Pendulum Squat", "name_fr": "Pendulum Squat", "muscle_group": "quads", "category": "machine", "is_compound": True},
    {"name_key": "exercise.belt_squat", "name_en": "Belt Squat", "name_fr": "Belt Squat", "muscle_group": "quads", "category": "machine", "is_compound": True},
    {"name_key": "exercise.wall_sit", "name_en": "Wall Sit", "name_fr": "Chaise", "muscle_group": "quads", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.pistol_squat", "name_en": "Pistol Squat", "name_fr": "Pistol Squat", "muscle_group": "quads", "category": "bodyweight", "is_compound": True},

    # ─── Hamstrings (Ischio-jambiers) ───────────────────────────
    {"name_key": "exercise.romanian_deadlift", "name_en": "Romanian Deadlift", "name_fr": "Soulevé de terre roumain", "muscle_group": "hamstrings", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.dumbbell_rdl", "name_en": "Dumbbell Romanian Deadlift", "name_fr": "Soulevé de terre roumain haltères", "muscle_group": "hamstrings", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.lying_leg_curl", "name_en": "Lying Leg Curl", "name_fr": "Leg curl allongé", "muscle_group": "hamstrings", "category": "machine", "is_compound": False},
    {"name_key": "exercise.seated_leg_curl", "name_en": "Seated Leg Curl", "name_fr": "Leg curl assis", "muscle_group": "hamstrings", "category": "machine", "is_compound": False},
    {"name_key": "exercise.stiff_leg_deadlift", "name_en": "Stiff Leg Deadlift", "name_fr": "Soulevé de terre jambes tendues", "muscle_group": "hamstrings", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.good_morning", "name_en": "Good Morning", "name_fr": "Good Morning", "muscle_group": "hamstrings", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.nordic_curl", "name_en": "Nordic Curl", "name_fr": "Nordic Curl", "muscle_group": "hamstrings", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.glute_ham_raise", "name_en": "Glute-Ham Raise", "name_fr": "Glute-Ham Raise", "muscle_group": "hamstrings", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.single_leg_rdl", "name_en": "Single Leg Romanian Deadlift", "name_fr": "Soulevé de terre roumain unipodal", "muscle_group": "hamstrings", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.cable_pull_through", "name_en": "Cable Pull Through", "name_fr": "Tirage entre les jambes", "muscle_group": "hamstrings", "category": "cable", "is_compound": True},

    # ─── Glutes (Fessiers) ──────────────────────────────────────
    {"name_key": "exercise.hip_thrust", "name_en": "Hip Thrust", "name_fr": "Hip Thrust", "muscle_group": "glutes", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.barbell_glute_bridge", "name_en": "Barbell Glute Bridge", "name_fr": "Pont fessier barre", "muscle_group": "glutes", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.single_leg_hip_thrust", "name_en": "Single Leg Hip Thrust", "name_fr": "Hip Thrust unipodal", "muscle_group": "glutes", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.cable_glute_kickback", "name_en": "Cable Kickback", "name_fr": "Kickback poulie fessiers", "muscle_group": "glutes", "category": "cable", "is_compound": False},
    {"name_key": "exercise.step_up", "name_en": "Step Up", "name_fr": "Step Up", "muscle_group": "glutes", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.sumo_deadlift", "name_en": "Sumo Deadlift", "name_fr": "Soulevé de terre sumo", "muscle_group": "glutes", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.hip_abduction", "name_en": "Hip Abduction Machine", "name_fr": "Abduction hanche machine", "muscle_group": "glutes", "category": "machine", "is_compound": False},
    {"name_key": "exercise.banded_clamshell", "name_en": "Banded Clamshell", "name_fr": "Clamshell avec élastique", "muscle_group": "glutes", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.donkey_kick", "name_en": "Donkey Kick", "name_fr": "Coup de pied âne", "muscle_group": "glutes", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.fire_hydrant", "name_en": "Fire Hydrant", "name_fr": "Bouche d'incendie", "muscle_group": "glutes", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.frog_pump", "name_en": "Frog Pump", "name_fr": "Frog Pump", "muscle_group": "glutes", "category": "bodyweight", "is_compound": False},

    # ─── Calves (Mollets) ───────────────────────────────────────
    {"name_key": "exercise.standing_calf_raise", "name_en": "Standing Calf Raise", "name_fr": "Extension mollets debout", "muscle_group": "calves", "category": "machine", "is_compound": False},
    {"name_key": "exercise.seated_calf_raise", "name_en": "Seated Calf Raise", "name_fr": "Extension mollets assis", "muscle_group": "calves", "category": "machine", "is_compound": False},
    {"name_key": "exercise.donkey_calf_raise", "name_en": "Donkey Calf Raise", "name_fr": "Extension mollets âne", "muscle_group": "calves", "category": "machine", "is_compound": False},
    {"name_key": "exercise.single_leg_calf_raise", "name_en": "Single Leg Calf Raise", "name_fr": "Extension mollet unipodal", "muscle_group": "calves", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.leg_press_calf_raise", "name_en": "Leg Press Calf Raise", "name_fr": "Extension mollets presse", "muscle_group": "calves", "category": "machine", "is_compound": False},
    {"name_key": "exercise.smith_calf_raise", "name_en": "Smith Machine Calf Raise", "name_fr": "Extension mollets Smith machine", "muscle_group": "calves", "category": "machine", "is_compound": False},
    {"name_key": "exercise.tibialis_raise", "name_en": "Tibialis Raise", "name_fr": "Extension tibial", "muscle_group": "calves", "category": "bodyweight", "is_compound": False},

    # ─── Abs (Abdominaux) ──────────────────────────────────────
    {"name_key": "exercise.crunch", "name_en": "Crunch", "name_fr": "Crunch", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.plank", "name_en": "Plank", "name_fr": "Planche", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.side_plank", "name_en": "Side Plank", "name_fr": "Planche latérale", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.hanging_leg_raise", "name_en": "Hanging Leg Raise", "name_fr": "Relevé de jambes suspendu", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.hanging_knee_raise", "name_en": "Hanging Knee Raise", "name_fr": "Relevé de genoux suspendu", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.russian_twist", "name_en": "Russian Twist", "name_fr": "Rotation russe", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.ab_wheel_rollout", "name_en": "Ab Wheel Rollout", "name_fr": "Roulette abdominale", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.cable_crunch", "name_en": "Cable Crunch", "name_fr": "Crunch poulie", "muscle_group": "abs", "category": "cable", "is_compound": False},
    {"name_key": "exercise.mountain_climber", "name_en": "Mountain Climber", "name_fr": "Mountain Climber", "muscle_group": "abs", "category": "bodyweight", "is_compound": True},
    {"name_key": "exercise.l_sit", "name_en": "L-Sit", "name_fr": "L-Sit", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.bicycle_crunch", "name_en": "Bicycle Crunch", "name_fr": "Crunch bicyclette", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.dead_bug", "name_en": "Dead Bug", "name_fr": "Dead Bug", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.woodchop", "name_en": "Woodchop", "name_fr": "Woodchop", "muscle_group": "abs", "category": "cable", "is_compound": True},
    {"name_key": "exercise.pallof_press", "name_en": "Pallof Press", "name_fr": "Pallof Press", "muscle_group": "abs", "category": "cable", "is_compound": False},
    {"name_key": "exercise.v_up", "name_en": "V-Up", "name_fr": "V-Up", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.toe_touch", "name_en": "Toe Touch", "name_fr": "Toucher d'orteils", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.flutter_kick", "name_en": "Flutter Kick", "name_fr": "Flutter Kick", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.dragon_flag", "name_en": "Dragon Flag", "name_fr": "Dragon Flag", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.leg_raise", "name_en": "Lying Leg Raise", "name_fr": "Relevé de jambes allongé", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.decline_crunch", "name_en": "Decline Crunch", "name_fr": "Crunch décliné", "muscle_group": "abs", "category": "bodyweight", "is_compound": False},

    # ─── Forearms (Avant-bras) ──────────────────────────────────
    {"name_key": "exercise.wrist_curl", "name_en": "Wrist Curl", "name_fr": "Curl poignet", "muscle_group": "forearms", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.reverse_wrist_curl", "name_en": "Reverse Wrist Curl", "name_fr": "Curl poignet inversé", "muscle_group": "forearms", "category": "dumbbell", "is_compound": False},
    {"name_key": "exercise.farmers_walk", "name_en": "Farmer's Walk", "name_fr": "Farmer's Walk", "muscle_group": "forearms", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.plate_pinch", "name_en": "Plate Pinch", "name_fr": "Pince de disque", "muscle_group": "forearms", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.dead_hang", "name_en": "Dead Hang", "name_fr": "Suspension passive", "muscle_group": "forearms", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.gripper", "name_en": "Hand Gripper", "name_fr": "Pince de main", "muscle_group": "forearms", "category": "bodyweight", "is_compound": False},
    {"name_key": "exercise.behind_back_wrist_curl", "name_en": "Behind Back Wrist Curl", "name_fr": "Curl poignet dos", "muscle_group": "forearms", "category": "barbell", "is_compound": False},

    # ─── Cardio ─────────────────────────────────────────────────
    {"name_key": "exercise.running", "name_en": "Running", "name_fr": "Course à pied", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.treadmill", "name_en": "Treadmill", "name_fr": "Tapis de course", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.cycling", "name_en": "Cycling", "name_fr": "Vélo", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.stationary_bike", "name_en": "Stationary Bike", "name_fr": "Vélo stationnaire", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.rowing_machine", "name_en": "Rowing Machine", "name_fr": "Rameur", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.jump_rope", "name_en": "Jump Rope", "name_fr": "Corde à sauter", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.swimming", "name_en": "Swimming", "name_fr": "Natation", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.stair_climber", "name_en": "Stair Climber", "name_fr": "Escalier", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.elliptical", "name_en": "Elliptical", "name_fr": "Elliptique", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.battle_ropes", "name_en": "Battle Ropes", "name_fr": "Cordes ondulatoires", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.burpees", "name_en": "Burpees", "name_fr": "Burpees", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.box_jump", "name_en": "Box Jump", "name_fr": "Box Jump", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.jumping_jacks", "name_en": "Jumping Jacks", "name_fr": "Jumping Jacks", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.sprints", "name_en": "Sprints", "name_fr": "Sprints", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.hiit", "name_en": "HIIT Session", "name_fr": "Séance HIIT", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.assault_bike", "name_en": "Assault Bike", "name_fr": "Vélo Assault", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.ski_erg", "name_en": "Ski Erg", "name_fr": "Ski Erg", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.sled_push", "name_en": "Sled Push", "name_fr": "Poussée de traîneau", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.sled_pull", "name_en": "Sled Pull", "name_fr": "Tirage de traîneau", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.high_knees", "name_en": "High Knees", "name_fr": "Montées de genoux", "muscle_group": "cardio", "category": "cardio", "is_compound": True},
    {"name_key": "exercise.butt_kicks", "name_en": "Butt Kicks", "name_fr": "Talons fesses", "muscle_group": "cardio", "category": "cardio", "is_compound": True},

    # ─── Full Body ──────────────────────────────────────────────
    {"name_key": "exercise.clean_and_jerk", "name_en": "Clean and Jerk", "name_fr": "Épaulé-jeté", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.snatch", "name_en": "Snatch", "name_fr": "Arraché", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.power_clean", "name_en": "Power Clean", "name_fr": "Épaulé", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.hang_clean", "name_en": "Hang Clean", "name_fr": "Épaulé suspendu", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.thruster", "name_en": "Thruster", "name_fr": "Thruster", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.turkish_get_up", "name_en": "Turkish Get-Up", "name_fr": "Turkish Get-Up", "muscle_group": "full_body", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.man_maker", "name_en": "Man Maker", "name_fr": "Man Maker", "muscle_group": "full_body", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.kettlebell_swing", "name_en": "Kettlebell Swing", "name_fr": "Swing kettlebell", "muscle_group": "full_body", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.clean_and_press", "name_en": "Clean and Press", "name_fr": "Épaulé-développé", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.devil_press", "name_en": "Devil Press", "name_fr": "Devil Press", "muscle_group": "full_body", "category": "dumbbell", "is_compound": True},
    {"name_key": "exercise.bear_complex", "name_en": "Bear Complex", "name_fr": "Bear Complex", "muscle_group": "full_body", "category": "barbell", "is_compound": True},
    {"name_key": "exercise.wall_ball", "name_en": "Wall Ball", "name_fr": "Wall Ball", "muscle_group": "full_body", "category": "bodyweight", "is_compound": True},

    # ─── Stretching ─────────────────────────────────────────────
    {"name_key": "exercise.hamstring_stretch", "name_en": "Hamstring Stretch", "name_fr": "Étirement ischio-jambiers", "muscle_group": "hamstrings", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.quad_stretch", "name_en": "Quad Stretch", "name_fr": "Étirement quadriceps", "muscle_group": "quads", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.hip_flexor_stretch", "name_en": "Hip Flexor Stretch", "name_fr": "Étirement fléchisseurs hanche", "muscle_group": "quads", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.chest_stretch", "name_en": "Chest Stretch", "name_fr": "Étirement pectoraux", "muscle_group": "chest", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.shoulder_stretch", "name_en": "Shoulder Stretch", "name_fr": "Étirement épaules", "muscle_group": "shoulders", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.tricep_stretch", "name_en": "Tricep Stretch", "name_fr": "Étirement triceps", "muscle_group": "triceps", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.lat_stretch", "name_en": "Lat Stretch", "name_fr": "Étirement dorsaux", "muscle_group": "back", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.calf_stretch", "name_en": "Calf Stretch", "name_fr": "Étirement mollets", "muscle_group": "calves", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.pigeon_pose", "name_en": "Pigeon Pose", "name_fr": "Posture du pigeon", "muscle_group": "glutes", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.cobra_stretch", "name_en": "Cobra Stretch", "name_fr": "Posture du cobra", "muscle_group": "abs", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.cat_cow", "name_en": "Cat-Cow Stretch", "name_fr": "Étirement chat-vache", "muscle_group": "back", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.child_pose", "name_en": "Child's Pose", "name_fr": "Posture de l'enfant", "muscle_group": "back", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.foam_rolling", "name_en": "Foam Rolling", "name_fr": "Rouleau de massage", "muscle_group": "full_body", "category": "stretching", "is_compound": False},
    {"name_key": "exercise.world_greatest_stretch", "name_en": "World's Greatest Stretch", "name_fr": "Meilleur étirement du monde", "muscle_group": "full_body", "category": "stretching", "is_compound": False},
]


async def seed_exercises(db: AsyncSession) -> None:
    result = await db.execute(select(func.count()).select_from(Exercise).where(Exercise.is_custom == False))  # noqa: E712
    count = result.scalar() or 0
    if count > 0:
        return

    exercises = [Exercise(**data) for data in EXERCISES]
    db.add_all(exercises)
    await db.commit()
