from app.schemas.auth import LoginRequest, RefreshRequest, TokenResponse
from app.schemas.body import (
    BodyMeasurementCreate,
    BodyMeasurementResponse,
    BodyMeasurementStats,
    ProgressPhotoResponse,
)
from app.schemas.community import CommentCreate, CommentResponse, PostCreate, PostResponse
from app.schemas.exercise import ExerciseCreate, ExerciseResponse, ExerciseUpdate
from app.schemas.nutrition import (
    DailyNutritionSummary,
    DailyWaterSummary,
    NutritionEntryCreate,
    NutritionEntryResponse,
    NutritionEntryUpdate,
    NutritionGoalCreate,
    NutritionGoalResponse,
    WaterIntakeCreate,
    WaterIntakeResponse,
)
from app.schemas.user import UserCreate, UserProfile, UserResponse, UserUpdate
from app.schemas.workout import (
    PersonalRecordResponse,
    ProgramDayCreate,
    ProgramDayResponse,
    ProgramDayUpdate,
    ProgramExerciseCreate,
    ProgramExerciseResponse,
    ProgramExerciseUpdate,
    SessionSetCreate,
    SessionSetResponse,
    SessionSetUpdate,
    WorkoutProgramCreate,
    WorkoutProgramResponse,
    WorkoutProgramUpdate,
    WorkoutSessionCreate,
    WorkoutSessionResponse,
    WorkoutSessionUpdate,
    WorkoutStats,
)

__all__ = [
    "LoginRequest",
    "RefreshRequest",
    "TokenResponse",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserProfile",
    "BodyMeasurementCreate",
    "BodyMeasurementResponse",
    "BodyMeasurementStats",
    "ProgressPhotoResponse",
    "ExerciseCreate",
    "ExerciseUpdate",
    "ExerciseResponse",
    "WorkoutProgramCreate",
    "WorkoutProgramUpdate",
    "WorkoutProgramResponse",
    "ProgramDayCreate",
    "ProgramDayUpdate",
    "ProgramDayResponse",
    "ProgramExerciseCreate",
    "ProgramExerciseUpdate",
    "ProgramExerciseResponse",
    "WorkoutSessionCreate",
    "WorkoutSessionUpdate",
    "WorkoutSessionResponse",
    "SessionSetCreate",
    "SessionSetUpdate",
    "SessionSetResponse",
    "PersonalRecordResponse",
    "WorkoutStats",
    "NutritionGoalCreate",
    "NutritionGoalResponse",
    "NutritionEntryCreate",
    "NutritionEntryUpdate",
    "NutritionEntryResponse",
    "DailyNutritionSummary",
    "WaterIntakeCreate",
    "WaterIntakeResponse",
    "DailyWaterSummary",
    "PostCreate",
    "PostResponse",
    "CommentCreate",
    "CommentResponse",
]
